version: '3'
services:
  server:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "5000:80"
    volumes:
      - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./app:/var/www/html/app"
    depends_on:
      - web
    links:
      - web
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    image: web:latest
    container_name: web
    restart: on-failure
    env_file: docker.env
    ports:
      - "9000:9000"
    volumes:
      - "./app:/var/www/html/app"
    depends_on:
      - rabbit
      - mongo
      - mailer
    links:
      - rabbit
      - mongo
      - mailer
  worker:
    build:
      context: .
      dockerfile: ./docker/worker/Dockerfile
    image: worker:latest
    container_name: worker
    restart: on-failure
    env_file: docker.env
    volumes:
      - "./app:/var/www/html/app"
    depends_on:
      - rabbit
      - mongo
      - mailer
    links:
      - mongo
      - mailer
      - rabbit
  mailer:
    image: schickling/mailcatcher
    container_name: mailer
    ports:
      - "1025:1025"
      - "1080:1080"
  rabbit:
    image: rabbitmq:management-alpine
    container_name: rabbit
    hostname: rabbit
    environment:
      - RABBITMQ_DEFAULT_VHOST=/
      - RABBITMQ_DEFAULT_USER=bzcontact
      - RABBITMQ_DEFAULT_PASS=docker
    ports:
      - "15672:15672"
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "./data/mongodb:/data/db"
