version: '3'
services:
  # server:
  #   image: nginx:alpine
  #   container_name: nginx
  #   ports:
  #     - "5000:5000"
  #   volumes:
  #     - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
  #     - "./app:/var/www/html/app"
  #   depends_on:
  #     - web
  #   links:
  #     - web
  # web:
  #   build:
  #     context: .
  #     dockerfile: ./docker/web/Dockerfile
  #   image: web:latest
  #   container_name: web
  #   env_file: .env
  #   ports:
  #     - "9000:9000"
  #   volumes:
  #     - "./app:/var/www/html/app"
  #   depends_on:
  #     - rabbit
  #     - mongo
  #   links:
  #     - rabbit
  #     - mongo
  worker:
    build:
      context: .
      dockerfile: ./docker/worker/Dockerfile
    image: worker:latest
    container_name: worker
    environment:
      - DATABASE_URI=mongodb://mongo:27017/local
      - DATABASE_COLLECTION=entries
    volumes:
      - "./app:/var/www/html/app"
    depends_on:
      - rabbit
      - mongo
      - mailer
    links:
      - rabbit
      - mongo
      - mailer
  mailer:
    image: schickling/mailcatcher
    container_name: mailer
    ports:
      - "1025:1025"
      - "1080:1080"
  rabbit:
    image: rabbitmq:management-alpine
    container_name: rabbit
    ports:
      - "15672:15672"
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "./data/mongodb:/data/db"
