
    <footer role="contentinfo">
        <div class="container">
            <p>
                <small>
                    (cc) 2016 BZ Coding Ltd. Some Rights Reserved.<br/>
                    Default UI theme built on top of <a href="http://getskeleton.com/">Skeleton</a>,
                    cover photo by <a href="https://unsplash.com/@yairhazout">Yair Hazout / Unsplash</a>.<br/>
                    Favicon by <a href="http://www.freepik.com" title="Freepik">Freepik</a> from <a href="http://www.flaticon.com" title="Flaticon">Flaticon</a>, licensed by <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a>
                </small>
            </p>
        </div>
    </footer>

<!-- <script src="js/scripts.js"></script> -->
</body>
</html>
