<!doctype html>

<html lang="en">
<head>
  <meta charset="utf-8">

  <title>BZ Contact</title>
  <meta name="description" content="Contact us">
  <meta name="author" content="Your (Company) Name">

  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Base Styles -->
  <link href="//fonts.googleapis.com/css?family=Raleway:400,300,600" rel="stylesheet" type="text/css">
  <link rel="stylesheet" href="css/normalize.css">
  <link rel="stylesheet" href="css/skeleton.css">

  <!-- Current Theme Styles -->
  <link rel="stylesheet" href="css/default/style.css">

  <!--[if lt IE 9]>
  <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

  <!-- Favicon for the current theme -->
  <link rel="icon" type="image/png" href="img/default/favicon.png">

</head>

<body>
