<?php require_once '_header.phtml'; ?>

  <section id="error" class="content error">

    <h1>Ops, something went wrong!</h1>

    <p>For some reason we were not able to process your request, but an administrator has been notified of this.</p>

    <p>If you keep seeing this nasty page, please write to <a href="mailto:<?=$support?>"><?=$support?></a>.</p>

  </section>

<?php require_once '_footer.phtml'; ?>
