<?php require_once '_header.phtml'; ?>

<main class="hero">
  <div class="container error error-500">
    <h1>Ops, something went wrong!</h1>
    <p class="lead">For some reason we were not able to process your request, but an administrator has been notified of this.</p>
    <p>If you keep seeing this nasty page, please write to <a href="mailto:<?=$support?>"><?=$support?></a>.</p>
  </div>
</main>

<?php require_once '_footer.phtml'; ?>
