---
- name: restart ntp
  service: name=ntp state=restarted

- name: restart iptables
  service: name=iptables state=restarted

- name: update timezone
  command: dpkg-reconfigure --frontend noninteractive tzdata
