---

# A sample PHP playbook

  - hosts: php

    become: yes
    become_user: "root"
    become_method: "sudo"

    # Customize vars for Apache, PHP or MySQL (see mysql playbook)
    vars:
      app_env_vars:
        - name: SLIM_MODE
          value: development

        - name: LOG_PATH
          value: /tmp/bzcontact.log

        - name: MAILER_FROM_NAME
          value: BZ Contact at Example Inc

        - name: MAILER_FROM_EMAIL
          value: hello@example.com

        - name: MAILER_ADMIN_EMAIL
          value: admin@example.com

        # Subject prefix, a space will be added
        - name: MAILER_SUBJECT
          value: '[BZ Contact]'

        - name: MAILER_HOST
          value: 10.0.2.2

        - name: MAILER_PORT
          value: 1025

        # - name: MAILER_USERNAME
        #   value: foo
        #
        # - name: MAILER_PASSWORD
        #   value: bar

        - name: DATABASE_HOST
          value: mongodb://127.0.0.1:27017

        - name: DATABASE_NAME
          value: bzcontact

        - name: DATABASE_COLLECTION
          value: entries

        # - name: DATABASE_USERNAME
        #   value: foo
        #
        # - name: DATABASE_PASSWORD
        #   value: bar

    roles:
      - { role: php-apache2, tags: ['php','apache2'] }
      - { role: mongodb, tags: ['mongodb'] }

    tasks:

      # Add MySQL tasks here (see mysql playbook)

      # Add Apache tasks here
      - name: copy app vhost file
        template:
          src: etc/apache2/vhost.conf
          dest: /etc/apache2/sites-available/000-bzcontact.conf
          owner: root
          group: root
          mode: 0644

      - name: enable website
        command: "a2ensite 000-bzcontact"
        args:
          creates: "/etc/apache2/sites-enabled/000-bzcontact.conf"
        notify:
          - reload apache2

      # See https://docs.ansible.com/ansible/composer_module.html
      - name: run composer install
        composer:
          command: install
          working_dir: /app

      - name: Hello PHP
        action: shell echo "Hello PHP!"
        register: result
      - debug: var=result.stdout

    handlers:
      - name: restart apache2
        action: service name=apache2 state=restarted

      - name: reload apache2
        action: service name=apache2 state=reloaded
